openapi: 3.0.0
info:
  title: Some OpenAPI spec
  description: Some OpenAPI Description.
  version: 0.1.0
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /users/{id}:
    get:
      summary: Returns a user by id.
      description: Some text
      responses:
        '200':
          description: Some text
          content:
            application/json:
              schema:
                type: string
      parameters:
        - name: id
          in: path
          required: true
    put:
      operationId: replaceUser
      summary: Replaces a user by id.
      description: Some text
      responses:
        '200':
          description: Some text
          content:
            application/json:
              schema:
                type: object
                properties:
                  oldRevision:
                    type: string
                  newRevision:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      parameters:
        - name: id
          in: path
          required: true
  /users:
    get:
      summary: Returns all users.
      description: Some text
      responses:
        '200':
          description: Some text
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserGet"
        '401':
          description: Some text
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: string
                  errorMessage:
                    type: string
    post:
      operationId: addUser
      summary: Adds a new user.
      description: Some text
      responses:
        '200':
          description: Some text
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
      parameters:
        - name: id
          in: path
          required: true
  /profiles:
    $ref: "#/components/pathItems/profiles"
components:
  pathItems:
    profiles:
      get:
        responses:
          '200':
            description: Returns all profiles.
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      user:
                        type: object
                        properties:
                          firstName:
                            type: string
                          lastName:
                            type: string
  schemas:
    UserGet:
      type: array
      items:
        type: string